pages:
 # key is the dirname of pages in src/pages, not including documentation and blogList that is related to markdown file
 home:
  # 首页配置
  zh-cn:
   title: '网易易游'
   keywords: '网易易游，网易，游戏，SDK'
  # home config
  en-us:
   title: 'EaseGame'
   keywords: 'EaseGame'
 community:
  # 社区页配置
  zh-cn:
   title: '网易易游'
   keywords: '网易易游，网易，游戏，SDK'
  # community page config
  en-us:
   title: 'EaseGame'
   keywords: 'EaseGame'
 blog:
  # 博客列表页配置
  zh-cn:
   title: '网易易游'
   keywords: '网易易游，网易，游戏，SDK'
  en-us:
   # blog list page config
   title: 'EaseGame'
   keywords: 'EaseGame'